AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: NestJS on AWS Lambda

Globals:
  Function:
    Timeout: 25
    Runtime: nodejs18.x
    Tracing: Active
    MemorySize: 512
    Architectures:
      - x86_64
  Api:
    TracingEnabled: true

Parameters:
  stage:
    Type: String
    Default: sandbox
    Description: (Required) the environment name of the deployment (e.g. sb, dev, ,qa, uat, prod), defaults to dev.
    AllowedValues:
      - sandbox
      - dev

Resources:
  GermanAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${stage}-german-api-rest"
      StageName: !Ref stage
      Cors:
        AllowMethods: "'OPTIONS,POST,GET,PUT,DELETE,PATCH'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  MyGreetingsNestJSLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/greetings/serverless.handler
      Runtime: nodejs18.x
      CodeUri: ./
      MemorySize: 256
      Timeout: 20
      Events:
        Greetings:
          Type: Api
          Properties:
            RestApiId: !Ref GermanAPIGateway
            Path: /greetings/{proxy+}
            Method: ANY
        RootPath:
          Type: Api
          Properties:
            RestApiId: !Ref GermanAPIGateway
            Path: /greetings
            Method: ANY
  MyProductsNestJSLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/products/serverless.handler
      Runtime: nodejs18.x
      CodeUri: ./
      MemorySize: 256
      Timeout: 20
      Events:
        Products:
          Type: Api
          Properties:
            RestApiId: !Ref GermanAPIGateway
            Path: /products/{proxy+}
            Method: ANY
        RootPath:
          Type: Api
          Properties:
            RestApiId: !Ref GermanAPIGateway
            Path: /products
            Method: ANY

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for the nestJs demo app"
    Value: !Sub "https://${GermanAPIGateway}.execute-api.${AWS::Region}.amazonaws.com/stage/"
