AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: NestJS on AWS Lambda

Resources:
  MyGreetingsNestJSLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/greetings/serverless.handler
      Runtime: nodejs18.x
      CodeUri: ./
      MemorySize: 256
      Timeout: 20
      Events:
        Greetings:
          Type: Api
          Properties:
            Path: /greetings/{proxy+}
            Method: ANY
        RootPath:
          Type: Api
          Properties:
            Path: /greetings
            Method: ANY
  MyProductsNestJSLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/products/serverless.handler
      Runtime: nodejs18.x
      CodeUri: ./
      MemorySize: 256
      Timeout: 20
      Events:
        Products:
          Type: Api
          Properties:
            Path: /products/{proxy+}
            Method: ANY
        RootPath:
          Type: Api
          Properties:
            Path: /products
            Method: ANY

Outputs:
  HelloWorldApi:
    Description: 'API Gateway endpoint URL for the HelloWorld function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'